feat: Add scala-cli script generator to verify jdk classes

diff --git a/.github/workflows/nightly-builds.yml b/.github/workflows/nightly-builds.yml
--- a/.github/workflows/nightly-builds.yml
+++ b/.github/workflows/nightly-builds.yml
@@ -179,3 +179,21 @@ jobs:
           sbt \
             -Dpekko.build.scalaVersion=${{ matrix.scalaVersion }} \
             "+~ ${{ matrix.scalaVersion }} publishLocal publishM2"
+
+      - name: Install scala-cli
+        if: ${{ contains('11,17,21', matrix.javaVersion) }}
+        run: |-
+          curl -sS "https://virtuslab.github.io/scala-cli-packages/KEY.gpg" | sudo gpg --dearmor  -o /etc/apt/trusted.gpg.d/scala-cli.gpg 2>/dev/null
+          sudo curl -s --compressed -o /etc/apt/sources.list.d/scala_cli_packages.list "https://virtuslab.github.io/scala-cli-packages/debian/scala_cli_packages.list"
+          sudo apt update
+          sudo apt install scala-cli
+
+      - name: Use Scala-CLI to verify jdk 9 classes
+        if: ${{ contains('11,17,21', matrix.javaVersion) }}
+        run: |-
+          scala-cli --version
+          echo "Starting verification with Scala-CLI"
+          scala-cli stream/target/scala-cli/VerifyJDK9Classes.sc && echo "Verification successful" || (
+          echo "Error when VerifyJDK9Classes"
+          exit 1
+          )
